export const MessageCodes = {
  OPERATION_SUCCESSFUL: 'OPERATION_SUCCESSFUL',
  RESOURCE_CREATED: 'RESOURCE_CREATED',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  PROCESS_ERROR: 'PROCESS_ERROR',
  UNCONTROLLER_ERROR: 'UNCONTROLLER_ERROR',
  SERVICE_NOT_AVAILABLE: 'SERVICE_NOT_AVAILABLE'
}
